"""inital

Revision ID: ec79382abf10
Revises: 
Create Date: 2021-09-01 18:08:46.812556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec79382abf10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('transitions', sa.Integer(), nullable=False),
    sa.Column('redirect_type', sa.Enum('default', 'speed'), nullable=True),
    sa.Column('real_link', sa.String(length=500), nullable=False),
    sa.Column('disposable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'uri'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
